### PR TITLE
Use getopt style short/long argument flags

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@patrislav1 What do you think? make it behave more similar to other tools...  a bit annoying the flag package don't support long options

**Comment by patrislav1** [comment]
you mean like python argparse? yes would be nice
isn't there a golang equivalent for it?

**Comment by patrislav1** [comment]
oh I see you already implemented it :open_mouth: 
I mean it would even better to have short aliases for common stuff like `-s, --charboxsize Character box size` etc. but don't know how straightforward it is to implement

**Comment by wader** [comment]
Yeap! im using https://github.com/rsc/getopt that support short/long but now i noticed that the standard library flag package do seem to allow `--flag` and `--flag=` and can probably workaround support short flag also. So maybe can skip using the getopt package. Will have a look.

Ideas for other short flags to support? maybe also if some flags should be renamed?

**Comment by wader** [comment]
Replaced by #34

**Pull request closed without merging**
